AssigneeType: &AssigneeType
  type: object
  required:
    - id
    - type
  properties:
    id:
      type: string
      description: The ID of the assignee.
      example: '9MPv9sWRs8zaQHfLsPDT'
    type:
      type: string
      enum: [users, groups]
      description: The type of the assignee.
      example: users

Assignee: &Assignee
  type: object
  required:
    - id
    - type
    - attributes
  properties:
    id:
      type: string
      description: The ID of the assignee.
      example: '9MPv9sWRs8zaQHfLsPDT'
    type:
      type: string
      description: The classification of the object (`"users"`, `"groups"`).
      example: users
    attributes:
      type: object
      description: The attributes associated with the resource. Groups will only contain name.
      properties:
        email:
          type: string
          description: The email of the assignee.
          example: 'example@user.com'
        subscription:
          type: string
          description: The subscription of the assignee.
          example: 'grc_full'
        name:
          type: string
          description: The name the assignee.
          example: 'Name Example'

AddRoleAssigneesRequest:
  type: object
  description: The parameters required to assign one or more users to a role.
  required:
    - data
  properties:
    data:
      type: array
      description: A list of assignee type and ids to assign to the role
      items: *AssigneeType

RemoveRoleAssigneesRequest:
  type: object
  description: The parameters required to remove one or more users or groups from a role.
  required:
    - data
  properties:
    data:
      type: array
      description: A list of assignee type and ids to remove from the role.
      items: *AssigneeType

GetRoleAssigneesResponse:
  type: object
  description: The data associated with the resource.
  required:
    - data
  properties:
    data:
      type: array
      description: The list of role assignees, can contain both users and groups.
      items: *Assignee
