get:
  tags:
    - Workflows
  operationId: getWorkflow
  summary: Get a workflow
  description: Get information about a workflow including all of its statuses, events and handlers if requested.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceUuidParam'
    - $ref: '../../components/parameters.yml#/includeWithWorkflowParam'
  responses:
    200:
      description: OK.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/SingleWorkflowResponseWithIncludes'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
patch:
  tags:
    - Workflows
  operationId: updateWorkflow
  summary: Update a workflow
  description: Make changes to metadata for an existing workflow, such as changing the name or the description.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceUuidParam'
  requestBody:
    description: The data required to update a workflow.
    required: true
    content:
      application/vnd.api+json:
        schema:
          $ref: '../../components/schemas.yml#/UpdateWorkflowPayload'
  responses:
    200:
      description: Updated.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/SingleWorkflowResponse'
    400:
      $ref: '../../components/responses.yml#/ResourceTypeMismatch'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
    415:
      $ref: '../../components/responses.yml#/NotJsonapiMediaType'
    422:
      description: |
        Unprocessable entity.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/Errors'
          example:
            errors:
              - status: 422
                source:
                  pointer: '/data/attributes/name'
                code: invalid_resource
                detail: can't be blank
delete:
  tags:
    - Workflows
  operationId: deleteWorkflow
  summary: Delete a workflow
  description: |
    Permanently delete a workflow.

    <strong>Locked workflows cannot be deleted.</strong>

    <strong>System workflows cannot be deleted.</strong>

    <strong>Workflows linked to an asset type or asset record type cannot be deleted.</strong>
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceUuidParam'
  responses:
    204:
      $ref: '../../components/responses.yml#/NoContent'
    400:
      $ref: '../../components/responses.yml#/MissingOrgId'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
