get:
  tags:
    - Roles
  operationId: getRoles
  summary: >
    List of roles
  description: Get a list of roles defined in the organization.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - in: query
      name: filter[role_type]
      description: The role type used to filter the roles list by. Allowed values are `platform` or `user`.
      required: false
      schema:
        type: string
        example: platform
    - in: query
      name: include
      description: Whether or not to return assignees with the response. Allowed value is `assignees`.
      required: false
      schema:
        type: string
        example: assignees
    - in: query
      name: filter[assignees][user_type]
      description: User types to filter the list of assignees by. Can be a comma seperated list of multiple types. Supported types are user, system, and root. Non supported types are ignored.
      required: false
      schema:
        type: string
        example: 'root,system'
  responses:
    200:
      description: OK.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/MultipleRolesResponse'
          example:
            data:
              - id: '5fe686da-282a-11eb-adc1-0242ac120002'
                type: roles
                attributes:
                  name: platform_admin
                  display_name: Platform Admin
                  description: Administrators for the platform.
                  permissions:
                    organization:
                      '123456':
                        manage_asset_types: true
                        use_bulk_importer: false
                        manage_roles: true
                        manage_workflows: false
                  org_id: '123456'
                  created_at: '2019-02-09T13:17:26Z'
                  created_by: 3NQ6XzAUxqJMnAQ7n4KF
                  updated_at: '2019-02-09T13:17:26Z'
                  updated_by: 3NQ6XzAUxqJMnAQ7n4KF
                  role_type: platform
              - id: '282a11eb-5fe6-86da-0002-0242ac12adc1'
                type: roles
                attributes:
                  name: user_role
                  display_name: User Role
                  description: a role of type user.
                  permissions:
                    asset_type:
                      '1234':
                        create_asset: true
                        delete_asset: true
                        read_asset_section_0: true
                        read_asset_section_1: false
                        read_asset_section_2: false
                        read_asset_section_3: false
                        read_asset_section_4: false
                        read_asset_section_5: true
                        read_asset_section_6: true
                        read_asset_section_7: false
                        read_asset_section_8: true
                        read_asset_section_9: true
                        update_asset_section_0: true
                        update_asset_section_1: false
                        update_asset_section_2: false
                        update_asset_section_3: false
                        update_asset_section_4: false
                        update_asset_section_5: false
                        update_asset_section_6: false
                        update_asset_section_7: false
                        update_asset_section_8: false
                        update_asset_section_9: false
                      '4321':
                        create_asset: false
                        delete_asset: false
                        read_asset_section_0: true
                        read_asset_section_1: false
                        read_asset_section_2: false
                        read_asset_section_3: false
                        read_asset_section_4: false
                        read_asset_section_5: true
                        read_asset_section_6: true
                        read_asset_section_7: false
                        read_asset_section_8: true
                        read_asset_section_9: true
                        update_asset_section_0: true
                        update_asset_section_1: false
                        update_asset_section_2: false
                        update_asset_section_3: false
                        update_asset_section_4: false
                        update_asset_section_5: false
                        update_asset_section_6: false
                        update_asset_section_7: false
                        update_asset_section_8: false
                        update_asset_section_9: false
                  org_id: '123456'
                  created_at: '2019-02-09T13:17:26Z'
                  created_by: 3NQ6XzAUxqJMnAQ7n4KF
                  updated_at: '2019-02-09T13:17:26Z'
                  updated_by: 3NQ6XzAUxqJMnAQ7n4KF
                  role_type: user
    400:
      $ref: '../../components/responses.yml#/SchemaValidationFailed'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'

post:
  tags:
    - Roles
  operationId: createRole
  summary: Create a role
  description: Create a new role from scratch.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
  requestBody:
    description: The data required to create a role.
    required: true
    content:
      application/vnd.api+json:
        schema:
          $ref: '../../components/schemas.yml#/CreateRoleRequest'
  responses:
    201:
      description: Created.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/GetRoleResponse'
          example:
            data:
              - id: '5fe686da-282a-11eb-adc1-0242ac120002'
                type: roles
                attributes:
                  name: platform_admin
                  display_name: Platform Admin
                  description: Administrators for the platform.
                  permissions: {}
                  org_id: '123456'
                  created_at: '2019-02-09T13:17:26Z'
                  created_by: 3NQ6XzAUxqJMnAQ7n4KF
                  updated_at: '2019-02-09T13:17:26Z'
                  updated_by: 3NQ6XzAUxqJMnAQ7n4KF
                  role_type: platform
    400:
      $ref: '../../components/responses.yml#/SchemaValidationFailed'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    422:
      $ref: '../../components/responses.yml#/NameNotUnique'
