# This file lists the API endpoints that R&D is committed to maintain and support. This file is a superset of the customer.yml file.
# Not all of these endpoints are public-facing. There is a non-publicized URL for viewing the public endpoints.
openapi: 3.0.2
servers:
  - url: 'https://apis.highbond-s3.com/v1'
info:
  $ref: ./components/metadata.yml#/info
#
# Paths (in addition to the base server URL) are the various end-points available.
#
paths:
  ####################################
  # Asset Type & Attribute Type paths
  ####################################
  # Asset Type paths
  /orgs/{org_id}/asset_types:
    $ref: ./paths/asset_types/asset_types.yml
  /orgs/{org_id}/asset_types/{id}:
    $ref: ./paths/asset_types/asset_type.yml
  # Related Attribute Type Asset Type paths
  /orgs/{org_id}/asset_types/{asset_type_id}/attribute_types:
    $ref: ./paths/asset_types/related_asset_type_attribute_types.yml
  /orgs/{org_id}/asset_types/{asset_type_id}/attribute_types/{id}:
    $ref: ./paths/asset_types/related_asset_type_attribute_type.yml
  # Relate Asset Type to Root Record Type paths
  /orgs/{org_id}/asset_types/{parent_id}/record_types/{child_id}:
    $ref: ./paths/asset_types/record_type_root_relationship.yml

  # Asset Record Type paths
  /orgs/{org_id}/record_types:
    $ref: ./paths/asset_types/record_types.yml
  /orgs/{org_id}/record_types/{id}:
    $ref: ./paths/asset_types/record_type.yml
  # Related Attribute Type Asset Record Type paths
  /orgs/{org_id}/record_types/{record_type_id}/attribute_types:
    $ref: ./paths/asset_types/related_record_type_attribute_types.yml
  /orgs/{org_id}/record_types/{record_type_id}/attribute_types/{id}:
    $ref: ./paths/asset_types/related_record_type_attribute_type.yml
  # Relate Asset Record Type to Asset Record Type paths
  /orgs/{org_id}/record_types/{parent_id}/record_types/{child_id}:
    $ref: ./paths/asset_types/record_type_child_relationship.yml

  # Attribute Type paths
  /orgs/{org_id}/attribute_types:
    $ref: ./paths/asset_types/attribute_types.yml
  /orgs/{org_id}/attribute_types/{id}:
    $ref: ./paths/asset_types/attribute_type.yml

  ##################################
  # Assets paths
  ##################################
  # Assets
  /orgs/{org_id}/asset_types/{asset_type_id}/assets:
    $ref: ./paths/assets/assets.yml
  /orgs/{org_id}/asset_types/{asset_type_id}/assets/{asset_id}:
    $ref: ./paths/assets/asset.yml

  # Asset Relationships
  /orgs/{org_id}/asset_types/{asset_type_id}/assets/{asset_id}/relationships:
    $ref: ./paths/assets/asset_relationships.yml

  # Asset Records
  /orgs/{org_id}/record_types/{record_type_id}/records:
    $ref: ./paths/assets/records.yml
  /orgs/{org_id}/record_types/{record_type_id}/records/{record_id}:
    $ref: ./paths/assets/record.yml

  # Asset Record Relationships
  /orgs/{org_id}/record_types/{record_type_id}/records/{record_id}/relationships:
    $ref: ./paths/assets/record_relationships.yml

  ##################################
  # Toolkits paths
  ##################################
  # Template toolkits
  /orgs/{org_id}/template_toolkits:
    $ref: ./paths/toolkits/template_toolkits.yml

  # Toolkits
  /orgs/{org_id}/toolkits:
    $ref: ./paths/toolkits/toolkits.yml
  /orgs/{org_id}/toolkits/{id}:
    $ref: ./paths/toolkits/toolkit.yml

  # Toolkit resources
  /orgs/{org_id}/toolkits/{id}/{toolkit_action}:
    $ref: ./paths/toolkits/toolkit_resources.yml

  ##################################
  # Accounts / Launchpad paths
  ##################################
  # Users
  /orgs/{org_id}/users:
    $ref: ./paths/users/users.yml
  /orgs/{org_id}/users/{uid}:
    $ref: ./paths/users/user.yml

security:
  - bearerToken: []
components:
  securitySchemes:
    bearerToken: # arbitrary name for the security scheme
      description: |
        HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a
        safe and secure way to access data, while protecting your account credentials.
      type: http
      scheme: bearer
      bearerFormat: oauth2 # optional, the value is not used