ActionRelationships: &ActionRelationships
  type: object
  description: The relationships associated with the resource.
  required:
    - issue
    - assigned_by
  properties:
    issue:
      type: object
      description: The attributes associated with the resource.
      required:
        - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: The ID of the issue.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"issues"`).
              example: issues
    assigned_by: &AssignedByRelationship
      type: object
      description: |
        The person who created the action. You can only specify users with a Professional Manager or Professional User role in the project this action belongs to.
      required:
        - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: |
                The unique identifier (UID) of the assigned user. For more information on obtaining this value, see
                <a href="#section/Making-requests">Making requests</a>.
              example: '3NQ6XzAUxqJMnAQ7n4KF'
            type:
              type: string
              description: The classification of the object (`"users"`).
              example: users
    cc_users: &cc_users
      type: object
      nullable: true
      description: |
        Specifies one or more users in a HighBond instance that are cc'ed on this action.
      required:
        - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
              - id
              - type
            properties:
              id:
                type: string
                description: |
                  The unique identifier (UID) of the user. For more information on obtaining this value, see
                  <a href="#section/Making-requests">Making requests</a>.
                example: '3NQ6XzAUxqJMnAQ7n4KF'
              type:
                type: string
                description: The classification of the object (`"users"`).
                example: users
    owner_user: &owner_user
      type: object
      nullable: true
      description: |
        Specifies the user in a HighBond instance that responsible for the action.
      required:
        - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
            - id
            - type
          properties:
            id:
              type: string
              description: |
                The unique identifier (UID) of the user. For more information on obtaining this value, see
                <a href="#section/Making-requests">Making requests</a>.
              example: '3NQ6XzAUxqJMnAQ7n4KF'
            type:
              type: string
              description: The classification of the object (`"users"`).
              example: users

Action: &Action
  type: object
  description: The data associated with the resource.
  required:
    - id
    - type
    - attributes
    - relationships
  properties:
    id: &id
      type: string
      description: The ID of the requested resource.
      example: 1
    type: &type
      type: string
      description: The classification of the object (`"actions"`).
      example: actions
    attributes:
      type: object
      description: The attributes associated with the resource.
      properties:
        title: &title
          type: string
          description: The title of the action.
          maxLength: 255
          example: Title of the action
        created_at: &created_at
          type: string
          description: The timestamp identifying when the action was created.
          example: '2019-02-09T13:17:26Z'
          format: date-time
        updated_at: &updated_at
          type: string
          description: The timestamp identifying when the action was updated.
          example: '2019-02-09T13:17:26Z'
          format: date-time
        owner_name: &owner_name
          type: string
          description: |
            The action owner. Specifying a person's name does not immediately send them an email notification about the action.
            However, if `send_recurring_reminder` is configured to `true`, recurring email reminders are sent to the action owner
            based on the frequency configured. This field becomes required if the `owner_user` relationship is not provided. For more information, see
            <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-action-reminders" target="_blank">Sending recurring
            action reminders</a>.
          example: Tom Wachowski
        owner_email: &owner_email
          type: string
          description: |
            The action owner’s email address. Specifying a person's email does not immediately send them an email notification
            about the action. However, if `send_recurring_reminder` is configured to `true`, recurring email reminders are sent to the action owner
            based on the frequency configured. This field becomes required if the `owner_user` relationship is not provided. For more information, see
            <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-action-reminders" target="_blank">Sending recurring
            action reminders</a>.
          example: tom.wachowski@greenhills.com
        send_recurring_reminder: &send_recurring_reminder
          type: boolean
          description: |
            If `true`, a recurring email reminder about the action is sent to the owner. If `false`, a recurring email reminder is not sent.
            Recurring reminder frequencies are configurable. For more information, see
            <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-action-reminders" target="_blank">Sending recurring
            action reminders</a>.
          example: true
        include_issue_details: &include_issue_details
          type: boolean
          description: |
            If `true`, the issue title and description fields are displayed to the action owner. Once the action owner clicks on the link to the
            action in the email, they can see the fields on the action page. If `false`, the fields are not displayed to the action owner.
          example: true
        include_remediation_details: &include_remediation_details
          type: boolean
          description: |
            If `true`, the remediation plan and remediation deadline fields are displayed to the action owner. Once the action owner clicks on the
            link to the action in the email, they can see the fields on the action page. If `false`, the fields are not displayed to the action owner.
          example: false
        description: &description
          type: string
          description: A detailed description of the action.
          maxLength: 524288
          example: <h1>Action heading</h1><p>Action description.</p>
        due_date: &due_date
          type: string
          description: Specifies the date the action must be completed by.
          example: '2020-01-02'
          format: date
        priority: &priority
          type: string
          description: |
            A user configurable classification that specifies the priority of the action. The options available depend
            on the <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-customize-terms" target="_blank">configuration of the
            project type</a>.
          example: 'high'
        closed: &closed
          type: boolean
          description: |
            Specifies the state of the action. An action can have one of the following states: `"open"` or `"closed"`. If `true`, the action
            is in a `"closed"` state. The action owner stops receiving recurring email notifications about the action. The link to the action
            in any previously sent email notifications also expires. If `false`, the action is in an `"open"` state. Recurring notifications
            about the action continue to be sent to the action owner.
          example: true
        completed_date: &completed_date
          type: string
          description: Specifies the date that the action was completed or addressed. This field is typically filled out by the issue owner.
          example: '2020-01-02'
          format: date
        status: &status
          type: string
          description: |
            A user configurable classification that specifies the current status of the action. The options available
            depend on the <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-customize-terms" target="_blank">configuration
            of the project type</a>. This field is typically filled out by the action owner.
          example: Audit Verifying
        submitted_on: &submitted_on
          type: string
          description: Specifies the date that the action was completed or addressed. This field is typically filled out by the action owner.
          example: '2020-01-02'
          format: date
        custom_attributes: &custom_attributes
          type: array
          description: An array of custom attributes defined by the user that are available on this object.
          items:
            type: object
            description: A user defined custom attribute value.
            properties:
              id:
                type: string
                description: The ID of the custom attribute that this custom attribute value is for. Optional if term is included.
                example: '42'
              term:
                type: string
                description: The user defined term used to identify the custom attribute. Optional if id is included.
                example: 'Custom Action Attribute'
              value:
                type: array
                description: The value or values (for multiselect) to set this custom attribute to.
                example: ['Custom Select Option Text']
                items:
                  type: string
        cc_contacts: &cc_contacts
          type: array
          description: An array of user emails
          nullable: true
          example: ['user@company.com', 'user1@company.com']
          items:
            type: string
    relationships: *ActionRelationships

ActionComment: &ActionComment
  type: object
  description: The data associated with the resource.
  required:
    - id
    - type
    - attributes
    - relationships
  properties:
    id:
      type: string
      description: The ID of the requested resource.
      example: '1'
    type:
      type: string
      description: The classification of the object (`"action_comments"`).
      example: action_comments
    attributes:
      type: object
      description: The attributes associated with the resource.
      properties:
        message_content:
          type: string
          description: The content of the action comment.
          example: Message content
        commenter_name:
          type: string
          description: The name of the user who created the action comment.
          example: Tom Wachowski
        commenter_email:
          type: string
          description: The email of the user who created the action comment.
          example: tom@example.com
        created_at:
          type: string
          description: The timestamp identifying when the action comment was created.
          example: '2021-06-09T13:17:26Z'
          format: date-time
        updated_at:
          type: string
          description: The timestamp identifying when the action comment was updated.
          example: '2021-06-09T13:17:26Z'
          format: date-time
    relationships:
      type: object
      description: The relationships associated with the resource.
      required:
        - action
      properties:
        action:
          type: object
          description: The attributes associated with the resource.
          required:
            - data
          properties:
            data:
              type: object
              description: The data associated with the resource.
              required:
                - id
                - type
              properties:
                id:
                  type: string
                  description: The ID of the action.
                  example: '1'
                type:
                  type: string
                  description: The classification of the object (`"actions"`).
                  example: actions
        commenter_user:
          type: object
          description: |
            The ID for the user who created the action comment. Can be `null` if commenter is an external user.
          required:
            - data
          properties:
            data:
              type: object
              description: The data associated with the resource.
              required:
                - id
                - type
              properties:
                id:
                  type: string
                  description: |
                    The unique identifier (UID) of the commenter user. For more information on obtaining this value, see
                    <a href="#section/Making-requests">Making requests</a>.
                  example: '3NQ6XzAUxqJMnAQ7n4KF'
                type:
                  type: string
                  description: The classification of the object (`"users"`).
                  example: users
CreateActionRequest:
  type: object
  required:
    - data
  properties:
    data:
      type: object
      description: The data associated with the resource.
      required:
        - type
        - attributes
        - relationships
      properties:
        type: *type
        attributes: &updateableAttributes
          type: object
          description: The attributes associated with the resource.
          required:
            - title
            - due_date
          properties:
            title: *title
            due_date: *due_date
            owner_name: *owner_name
            owner_email: *owner_email
            created_at: *created_at
            updated_at: *updated_at
            send_recurring_reminder: *send_recurring_reminder
            include_issue_details: *include_issue_details
            include_remediation_details: *include_remediation_details
            description: *description
            priority: *priority
            closed: *closed
            completed_date: *completed_date
            status: *status
            submitted_on: *submitted_on
            custom_attributes: *custom_attributes
            cc_contacts: *cc_contacts
        relationships:
          type: object
          description: The relationships associated with the resource.
          required:
            - assigned_by
          properties:
            assigned_by: *AssignedByRelationship
            cc_users: *cc_users
            owner_user: *owner_user

UpdateActionRequest:
  type: object
  required:
    - data
  properties:
    data:
      type: object
      description: The data associated with the resource.
      required:
        - id
        - type
        - attributes
        - relationships
      properties:
        id: *id
        type: *type
        attributes: *updateableAttributes
        relationships:
          type: object
          description: The relationships associated with the resource.
          required:
            - assigned_by
          properties:
            assigned_by: *AssignedByRelationship
            cc_users: *cc_users
            owner_user: *owner_user

ActionCommentsIncluded: &ActionCommentsIncluded
  type: array
  description: The related comments included with the resource.
  items: *ActionComment

GetActionResponse:
  type: object
  required:
    - data
  properties:
    data: *Action

GetActionResponseWithIncluded:
  type: object
  required:
    - data
  properties:
    data: *Action
    included: *ActionCommentsIncluded

Links: &Links
  type: object
  required:
    - next
    - prev
  properties:
    next:
      type: string
      description: Next page url
      nullable: true
      example: '/api/resource?page[number]=Mg=='
    prev:
      type: string
      description: Previous page url
      nullable: true
      example: null

GetActionsResponse:
  type: object
  required:
    - data
    - included
    - links
  properties:
    data:
      type: array
      description: Array of actions
      items: *Action
    included:
      type: array
      description: Array of related action comments
      items: *ActionComment
    links: *Links

GetActionCommentsResponse:
  type: object
  required:
    - data
    - links
  properties:
    data:
      type: array
      description: Array of action comments
      items: *ActionComment
    links: *Links
