get:
  tags:
    - Projects
  operationId: getProject
  summary: Get a project
  description: Get information about a project. You can retrieve projects in the state `"active"`, `"archive"`, or `"delete"`.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceIdParam'
    - $ref: '../../components/parameters.yml#/projectSparseFieldsetParams'
  responses:
    200:
      description: OK.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/GetProjectResponseWithIncludes'
    400:
      $ref: '../../components/responses.yml#/MissingResourceId'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
    415:
      $ref: '../../components/responses.yml#/NotJsonapiMediaType'
patch:
  tags:
    - Projects
  operationId: updateProject
  summary: Update a project
  description: |
    Make changes to a project. Only projects in the state `"active"` or `"delete"` can be updated. Projects in the state `"archive"` cannot be updated.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceIdParam'
    - $ref: '../../components/parameters.yml#/projectSparseFieldsetParams'
  requestBody:
    description: The data required to update a project.
    required: true
    content:
      application/vnd.api+json:
        schema:
          $ref: '../../components/schemas.yml#/UpdateProjectRequest'
  responses:
    200:
      description: OK.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/GetProjectResponseWithIncludes'
    400:
      $ref: '../../components/responses.yml#/MissingResourceId'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
    415:
      $ref: '../../components/responses.yml#/NotJsonapiMediaType'
    422:
      description: |
        Unprocessable entity.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/Errors'
          example:
            errors:
              - status: 422
                source:
                  pointer: '/data/attributes/name'
                code: invalid_resource
                detail: can't be blank
              - status: 422
                source:
                  pointer: '/data/attributes/entities'
                code: invalid_resource
                detail: 'Missing child or parent entity ids: [1, 2 ,3]'
              - status: 422
                source:
                  pointer: '/data/attributes/entities'
                code: invalid_resource
                detail: 'Entities not found'
delete:
  tags:
    - Projects
  operationId: deleteProject
  summary: Delete a project
  description: |
    Delete a project that you no longer require. Projects in the state `"active"`, `"archived"` or `"delete"` can be deleted.

    You can temporarily or permanently delete a project:
    * By default, projects are temporarily deleted. The project is moved to a `"delete"` state and stored in the Project Library for 30 days. Project
    Admins receive an email notification when a project has been temporarily deleted. After 30 days, the project is permanently deleted automatically.
    * To request a permanent deletion of a project, you must specify `"delete"` using the `permanent` parameter. Project Admins do not receive
    an email notification when a project is permanently deleted.

    > **Caution —**
    Once a project is permanently deleted, you cannot access or restore the project.

    For more information, see <a href="https://help.highbond.com/helpdocs/highbond/en-us/Default.htm#cshid=pm-delete-project" target="_blank">Deleting
    and restoring projects</a>.
  parameters:
    - $ref: '../../components/parameters.yml#/orgIdParam'
    - $ref: '../../components/parameters.yml#/resourceIdParam'
    - $ref: '../../components/parameters.yml#/projectPermanentDeleteParam'
  responses:
    200:
      description: OK. [The project is temporarily deleted.]
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/GetProjectResponse'
    202:
      description: Accepted. [The project is queued for permanent deletion.]
    400:
      $ref: '../../components/responses.yml#/MissingResourceId'
    401:
      $ref: '../../components/responses.yml#/BadCredentials'
    403:
      $ref: '../../components/responses.yml#/Forbidden'
    404:
      $ref: '../../components/responses.yml#/NotFound'
    415:
      $ref: '../../components/responses.yml#/NotJsonapiMediaType'
    422:
      description: |
        Unprocessable entity.
      content:
        application/vnd.api+json:
          schema:
            $ref: '../../components/schemas.yml#/Errors'
          example:
            errors:
              - status: 422
                source:
                  pointer: '/data/attributes/state'
                code: invalid_resource
                detail: Invalid project state for the requested action.
